### PR TITLE
Removed breaking addition of X11, reinstated zswap

### PR DESCRIPTION
**Pull request by computermouth**
At the HEAD, I encountered a couple build failures with the addition of X11.

1. apitrace -- someone in the gcw0 world added some patches that perform some config workarounds as long as X11 isn't present. When X is present though, the build breaks.

At first I just replaced apitrace with the upstream buildroot package. I figured "who's doing GL debugging on this thing anyways?" But then...

2. classpath -- I'm not sure why this one is failing. Looks like it's pulled in by jamvm, which it looks like some people in the forum requested for java development.

Ultimately, I wonder why X was getting added. I was under the impression the entire UI and all apps ran without X.

Additionally, I put the zswap back. zswap isn't a normal swap, it's a kernel feature that starts compressing a chunk of your ram when you start running out. So I put it back in, it might even be a good idea to increase it to like 50MB.

Cheers!

### CODE REVIEW

**Comment by computermouth** [comment]
Actually, the build still fails on classpath.

Looks like the upstream removed JAMVM, probably for the same reason:
https://github.com/gcwnow/buildroot/commit/96484fa2eaef222eaa060fa01ce521f3d7805580#diff-a25736e8ccd66a8330f9e5b0533bb0dcL102

**Comment by computermouth** [comment]
Adding another fix for od-network installation failing, disabled jamvm.

I also had to disable libshake and that flappybird clone. Something was failing in the cflags or ldflags. I can't remember, so I've left it in the defconfig.

**Comment by glebm** [comment]
@soarqin https://github.com/tonyjih/RG350_buildroot/commit/c384eaf415e06233d5bcae95da8da0a0d6066b7e does break the build

**Comment by soarqin** [comment]
for classpath, you should install openjdk 1.8 or earlier version and make it the default jdk to get building success.
for X11, @steward-fu said some 3rd party games need it, and it was building fine on my linux, can you provide error messages in your build process?

**Comment by steward-fu** [comment]
build with libX11 is fine but don't enable check item on X11 server.
Is it possible to provide your .config to us, I think it can help us to find out root cause more quickly.

**Comment by computermouth** [comment]
Well I just used the regular defconfigs and stuff. Sounds like both the problems I had here are sorted.

1. X11 shouldn't be enabled (but I am curious as to what's using libX11 without an X server)
2. I installed openjdk11, so sounds like it was a problem with my host tools. Which would explain why you folks haven't run into it. Is 1.8 truly the correct version? The oldest JDK I can find is 6.

EDIT: looks like it's just naming conventions. On the yum family it's java-1.8.0-openjdk, on debian it's openjdk-8-jdk

**Comment by soarqin** [comment]
@glebm @computermouth I saw what was wrong in #28, check if #34 can fix it

**Comment by computermouth** [comment]
Closing in favor of https://github.com/tonyjih/RG350_buildroot/pull/34

**Pull request closed without merging**
