### PR TITLE
add exfat/ntfs support

### PR DESCRIPTION
**Pull request by soarqin**
1. added exfat-fuse support
2. added ntfs-3g support
3. auto mount exfat/ntfs partitions for mmc devices

### CODE REVIEW

**Comment by jdefields** [comment]
I'm against auto resize unless there is a graphical output that shows the progress.  Does this indicate the status on the built in screen.

**Comment by soarqin** [comment]
@jbd1986 agree, we'd better make a standalone app to do partition resize, I will remove it from pr later.

**Comment by soarqin** [comment]
@jbd1986 force pushed the new commit, removed partition resize

**Comment by soarqin** [comment]
after days' test, everything is working find. think this can be merged.

**Pull request merged**
