### PR TITLE
fix build of external packages, fix apitrace broken after #28, restore zswap use

### PR DESCRIPTION
**Pull request by soarqin**

### CODE REVIEW

**Comment by glebm** [comment]
From this PR:

```
make clean
make
...
>>> classpath 0.98 Autoreconfiguring
...
checking jni_md.h support... configure: WARNING: no
checking whether to enable maintainer-specific portions of Makefiles... no
checking for mkdir... /usr/bin/mkdir
checking for cp... /usr/bin/cp
checking for date... /usr/bin/date
checking for find... /usr/bin/find
checking for zip... /usr/bin/zip
checking for a jar-like tool... trying fastjar, gjar and jar
checking for fastjar... no
checking for gjar... no
checking for jar... /usr/bin/jar
checking whether to regenerate parsers with jay... no
checking for stdint types... stdint.h (shortcircuit)
make use of stdint.h in include/config-int.h (assuming C99 compatible system)
checking for ecj... no
checking for ecj-3.3... no
checking for ecj-3.2... no
checking for javac... javac -Xlint:unchecked,cast,divzero,empty,finally,overrides
checking if javac -Xlint:unchecked,cast,divzero,empty,finally,overrides is a version of gcj... 
checking if javac -Xlint:unchecked,cast,divzero,empty,finally,overrides works... configure: error: The Java compiler javac -Xlint:unchecked,cast,divzero,empty,finally,overrides failed (see config.log, check the CLASSPATH?)
make: *** [package/pkg-generic.mk:170: /home/gleb/repos/glebm/RG350_buildroot/output/build/classpath-0.98/.stamp_configured] Error 1
```

**Comment by glebm** [comment]
Detailed error in config.log:

```
configure:24619: javac -Xlint:unchecked,cast,divzero,empty,finally,overrides  -source 1.5 -target 1.5 Object.java
warning: [options] bootstrap class path not set in conjunction with -source 5
error: Source option 5 is no longer supported. Use 7 or later.
error: Target option 5 is no longer supported. Use 7 or later.
```

Looks like my host JDK is too new

**Comment by glebm** [comment]
I think we should just switch from JamVM to OpenJDK at this point. The last GNU classpath release was 7 years ago.

**Comment by glebm** [comment]
Let's get rid of `BR2_PACKAGE_JAMVM` for now.

**Comment by glebm** [comment]
@soarqin Sent you https://github.com/soarqin/RG350_buildroot/pull/1 to disable JamVM.

**Comment by glebm** [comment]
SDL2_ttf build fails with:

/home/gleb/repos/glebm/RG350_buildroot/output/host/usr/lib/gcc/mipsel-gcw0-linux-uclibc/4.9.1/../../../../mipsel-gcw0-linux-uclibc/bin/ld: cannot find -lGL

**Comment by soarqin** [comment]
@glebm please use jdk8, all common linux distros have it in official software manager

**Comment by glebm** [comment]
Which games actually use jamvm? Why keep it around?

**Comment by computermouth** [comment]
> all common linux distros have it in official software manager

Actually, I had to disable it because debian doesn't package it in their latest version. The rest of the changes look good to me, thanks!

I'll try a clean build later.

**Comment by glebm** [comment]
The easiest non-intrusive way to use JDK8 is via the asdf version manager:

```bash
# https://github.com/asdf-vm/asdf
asdf plugin add java
asdf install java adopt-openjdk-8u232-b09
asdf local java adopt-openjdk-8u232-b09
```

I still think we should just remove this classpath/JamVM stuff

**Comment by glebm** [comment]
It built! Going to make and run an update OPK and report back

**Comment by glebm** [comment]
Update OPK worked! All good!

**Pull request merged**
